name = "sdf_fonts"
description = "A simple library to render SDF fonts"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/sdf-fonts"
tags = []

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty", "-gnaty-B"]
development.contracts = "Yes"
"*".debug_info = "Yes"
