# SPDX-FileCopyrightText: 2026 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name = "stdout"
description = "Draw on stdout"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["stdout"]

[build-switches]
development.optimization = ["-O0"]

[[depends-on]]
sdf_fonts = "*"

[build-profiles]
"sdf_fonts" = "development"

[[pins]]
sdf_fonts = { path='../..' }
